server:
  port: 8090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cinema.notify.service@gmail.com
    password: biomvzbxytcbquzz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true